### ISSUE TITLE
Nothing was implemented

### ISSUE THREAD

**Issue by monacofj** [so-ii-2019/sh19-so2-raft_keicha#1]
It seems nothing was implemented.

**Comment by brunokeichi** [comment]
Bom dia, professor
Acabei enviando 2 branches (trabalho_v1 e trabalho_v2) e não dei pull request para dar merge no Master. Não sei se isso foi o problema de não estar nada implementado.

**Comment by monacofj** [comment]
Ok, entendido.
Fiz merge do trabalho_v2 no master para simplificar as coisas.
